### ISSUE TITLE
Logo in header disappears when scrolling all the way up

### ISSUE THREAD

**Issue by charredUtensil** [tdwtf/WtfWebApp#103]
If you scroll all the way up, past the top of the page, the logo on the top left disappears. This is only possible in Safari/Chrome on OSX or iOS, which allow you to scroll slightly above the page for a brief time before "springing" back.

**Comment by charredUtensil** [comment]
I took a peek into this again. Scrolling above the page causes the navbar to change class from `navbar dailywtf fixed` to `navbar dailywtf unfixed`, and the rest of the css will only display the logo if it is contained in the fixed navbar:

```css
.navbar.dailywtf.fixed .logo {
  margin: 9px 6px 6px 0;
  max-width: inherit;
  height: 45px;
}
.navbar.dailywtf.fixed .logo {
  display: block;
  margin: 11px 6px 6px -11px;
  float: left;
}
.navbar.dailywtf .logo {
  display: none;
}
```
