### ISSUE TITLE
Syntax-highlighted code is not in a monospace font

### ISSUE THREAD

**Issue by tbodt** [tdwtf/WtfWebApp#150]
This is because this CSS rule:

```css
h1, h2, h3, h4, h5, h6, p, a, span, li {
    font-family: "Open Sans";
}
```

overrides this rule:

```css
pre, code {
    font-family: monospace;
}
```

I would remove the first rule entirely. Any of the tags listed should inherit the correct font from this rule:

```css
body {
    background-color: @tdwtf-light-grey;
    font-family: "Open Sans";
}
```
